Repository vuejs/vitepress, pull requests merged in 2020-11, with the labels that each got.

#108 feat(client): support homepages feature
  src/client/app/composables/siteData.ts
  src/client/theme-default/Layout.vue
  src/client/theme-default/components/Home.vue
  src/client/theme-default/styles/layout.css
Labels: enhancement

#114 build: handle shared files better (#72)
  .gitignore
  package.json
  scripts/copyClient.js
  scripts/copyShared.js
  scripts/watchAndCopy.js
  src/client/tsconfig.json
  src/node/config.ts
  src/node/tsconfig.json
  src/shared/config.ts
  src/shared/tsconfig.json
Labels: enhancement

#123 fix($theme-default): display header-anchor links when using keyboard navigation
  src/client/theme-default/styles/layout.css
Labels: enhancement

#128 feat: add ability to configure markdown options (#127)
  src/node/build/bundle.ts
  src/node/config.ts
  src/node/server.ts
Labels: enhancement

#129 fix(client): show top part of scrollbar in sidebar
  src/client/theme-default/styles/layout.css
Labels: bug

#131 chore: add undeclared deps
  package.json
  yarn.lock
Labels: enhancement

#136 feat: add serve command
  bin/vitepress.js
  docs/.vitepress/config.js
  docs/guide/deploy.md
  docs/guide/getting-started.md
  package.json
  src/node/index.ts
  src/node/serve/serve.ts
  yarn.lock
Labels: enhancement

#130 fix: fix next and prev links not working
  src/client/theme-default/components/EditLink.vue
  src/client/theme-default/components/NextAndPrevLinks.ts
  src/client/theme-default/components/NextAndPrevLinks.vue
  src/client/theme-default/composables/nextAndPrevLinks.ts
  src/client/theme-default/utils.ts
  src/node/server.ts
  types/shared.d.ts
Labels: bug

#138 test: add unit test setup
  .gitignore
  __tests__/client/theme-default/utils.spec.ts
  jest.config.js
  package.json
  src/client/tsconfig.json
  src/node/tsconfig.json
  src/shared/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  yarn.lock
Labels: test

#139 Ensure that the base is used for previous and next links
  src/client/theme-default/components/NextAndPrevLinks.vue
Labels: bug

#142 fix: code plugins styles
  docs/guide/getting-started.md
  src/client/theme-default/styles/code.css
  src/client/theme-default/styles/vars.css
Labels: bug

#143 fix: mixed rgba colors for md code plugins
  src/client/theme-default/styles/code.css
Labels: bug

#144 docs: fix typo
  docs/guide/configuration.md
Labels: documentation

#145 docs: initial port of markdown extensions guide from VuePress
  docs/.vitepress/config.js
  docs/guide/markdown.md
  docs/images/line-numbers-desktop.png
  docs/images/line-numbers-mobile.gif
Labels: documentation

#146 fix: make code block look prettier
  src/client/theme-default/styles/code.css
  src/client/theme-default/styles/layout.css
  src/client/theme-default/styles/vars.css
Labels: bug

#148 docs: Modify VuePress to VitePress
  docs/guide/deploy.md
  docs/guide/getting-started.md
Labels: documentation

#149 fix: fix sidebar active status not working as expected (#140)
  src/client/theme-default/composables/activeSidebarLink.ts
Labels: bug

#150 fix: hydration mismatch
  src/client/theme-default/components/LastUpdated.vue
Labels: bug

#151 docs: port formatter guide from vuepress
  docs/.vitepress/config.js
  docs/guide/frontmatter.md
  docs/guide/markdown.md
Labels: documentation

#137 refactor: migrate default theme to use script-setup
  package.json
  src/client/theme-default/Layout.vue
  src/client/theme-default/NotFound.vue
  src/client/theme-default/components/EditLink.vue
  src/client/theme-default/components/Home.vue
  src/client/theme-default/components/NavBar.vue
  src/client/theme-default/components/NavBarLink.ts
  src/client/theme-default/components/NavBarLink.vue
  src/client/theme-default/components/NavBarLinks.ts
  src/client/theme-default/components/NavBarLinks.vue
  src/client/theme-default/components/NavDropdownLink.ts
  src/client/theme-default/components/NavDropdownLink.vue
  src/client/theme-default/components/NextAndPrevLinks.vue
  src/client/theme-default/components/Page.vue
  src/client/theme-default/components/SideBar.vue
  src/client/theme-default/components/SideBarLinks.vue
  src/node/build/build.ts
  src/node/build/bundle.ts
  src/node/markdownToVue.ts
  yarn.lock
Labels: enhancement

#152 feat: frontmatter global and computed global docs
  docs/.vitepress/config.js
  docs/guide/frontmatter.md
  docs/guide/global-computed.md
  src/client/app/index.ts
  src/client/theme-default/components/NavBarTitle.vue
  src/node/markdownToVue.ts
  types/shared.d.ts
Labels: enhancement

#86 feat(default-theme): native support for carbon ads
  docs/.vitepress/config.js
  docs/config/carbon-ads.md
  src/client/theme-default/Layout.vue
  src/client/theme-default/components/BuySellAds.vue
  src/client/theme-default/components/CarbonAds.vue
  src/client/theme-default/styles/custom-blocks.css
  src/client/theme-default/styles/vars.css
Labels: enhancement

#156 docs: port of assets page from vuepress
  docs/.vitepress/config.js
  docs/guide/assets.md
  docs/guide/global-computed.md
Labels: documentation

#161 Update basics.md
  docs/config/basics.md
Labels: documentation

#163 fix: align $title with vuepress (#158)
  src/client/app/mixin.ts
Labels: bug

#154 fix: make home page look better
  docs/.vitepress/config.js
  docs/config/homepage.md
  src/client/app/composables/frontmatter.ts
  src/client/app/exports.ts
  src/client/theme-default/Layout.vue
  src/client/theme-default/components/Home.vue
  src/client/theme-default/components/HomeFeatures.vue
  src/client/theme-default/components/HomeFooter.vue
  src/client/theme-default/components/HomeHero.vue
  src/client/theme-default/styles/layout.css
Labels: bug

#162 docs: port deploy instructions for common services from vuepress
  docs/guide/deploy.md
  docs/images/vercel-configuration.png
Labels: documentation

#153 feat: add Algolia DocSearch (#40)
  docs/.vitepress/config.js
  package.json
  src/client/theme-default/Layout.vue
  src/client/theme-default/components/AlgoliaSearchBox.vue
  src/client/theme-default/styles/vars.css
  yarn.lock
Labels: enhancement

#165 fix: prevLinks and nextLinks config type
  src/client/theme-default/config.ts
Labels: bug, types
