Repository vuejs/vitepress, pull requests merged in 2021-02, with the labels that each got.

#210 Make serve url clickable
  src/node/serve/serve.ts
Labels: enhancement

#223 fix: `base` option not working on dev mode (#181)
  src/node/server.ts
Labels: bug

#164 docs: add migrating from vuepress guide
  docs/.vitepress/config.js
  docs/guide/differences-from-vuepress.md
Labels: documentation

#170 fix: frontmatter description duplication (#194)
  src/client/app/composables/head.ts
  src/node/build/render.ts
  src/node/markdownToVue.ts
Labels: enhancement

#224 fix: sidebar 'auto' not working (#178)
  __tests__/client/theme-default/support/sideBar.spec.ts
  src/client/theme-default/Layout.vue
  src/client/theme-default/support/sideBar.ts
Labels: bug

#207 fix: render document with standards mode
  src/node/plugin.ts
Labels: enhancement

#228 fix: utf-8 character not working on safari in dev mode (#218)
  src/node/plugin.ts
Labels: bug

#204 snippet plugin root params Missing default value
  src/node/markdown/markdown.ts
  src/node/markdownToVue.ts
Labels: bug

#212 fix: HomeHero NavLink reactivity lost (#195)
  src/client/theme-default/components/NavDropdownLinkItem.vue
  src/client/theme-default/components/NavLink.vue
  src/client/theme-default/composables/navLink.ts
Labels: bug

#233 fix: nav home title not having locale based link (#195)
  src/client/theme-default/components/NavBarTitle.vue
Labels: bug

#234 fix: `base` option not generating correct multi sidebar (#231)
  src/client/theme-default/Layout.vue
  src/client/theme-default/components/SideBarLink.ts
  src/client/theme-default/composables/navLink.ts
  src/client/theme-default/composables/sideBar.ts
  src/client/theme-default/utils.ts
Labels: bug
