Repository vuejs/vitepress, pull requests merged in 2022-08, with the labels that each got.

#843 refactor: externalize markdown component plugin
  package.json
  pnpm-lock.yaml
  src/node/markdown/markdown.ts
  src/node/markdown/plugins/component.ts
Labels: enhancement, dependencies, build

#1224 docs: clarify GitHub Pages deployment instructions
  docs/guide/deploying.md
Labels: docs

#644 perf(a11y): add aria-checked attribute to switch
  src/client/theme-default/components/VPSwitchAppearance.vue
Labels: enhancement
