Repository vuejs/vitepress, pull requests merged in 2024-10, with the labels that each got.

#4066 fix: disable autocomplete in LocalSearchBox
  src/client/theme-default/components/VPLocalSearchBox.vue
Labels: stale, cr-tracked

#4067 Add info about the `{open}` attr. for `details` container
  docs/en/guide/markdown.md
Labels: stale

#4286 fix(theme): remove some explicit fonts
  src/client/theme-default/styles/vars.css
Labels: needs more discussion, cr-tracked

#4308 feat(theme): don't escape `siteTitle`
  src/client/theme-default/components/VPNavBarTitle.vue
Labels: cr-tracked

#4321 perf: cache shiki
  package.json
  pnpm-lock.yaml
  src/node/contentLoader.ts
  src/node/markdown/markdown.ts
  src/node/markdown/plugins/highlight.ts
  src/node/plugin.ts
Labels: cr-tracked
