Repository vuejs/vitepress, pull requests merged in 2025-02, with the labels that each got.

#4271 feat(cli): support custom npm scripts prefix
  src/node/init/init.ts
Labels: stale

#4270 feat(cli): support custom `srcDir`
  src/node/init/init.ts
  template/.vitepress/config.js
Labels: stale

#4525 feat!: dynamic routes plugin overhaul
  __tests__/e2e/dynamic-routes/[id].paths.ts
  __tests__/e2e/dynamic-routes/paths.ts
  __tests__/unit/node/utils/moduleGraph.test.ts
  src/client/app/data.ts
  src/client/theme-default/components/VPLocalSearchBox.vue
  src/node/config.ts
  src/node/index.ts
  src/node/init/init.ts
  src/node/markdownToVue.ts
  src/node/plugin.ts
  src/node/plugins/dynamicRoutesPlugin.ts
  src/node/plugins/localSearchPlugin.ts
  src/node/plugins/staticDataPlugin.ts
  src/node/siteConfig.ts
  src/node/utils/moduleGraph.ts
  src/node/utils/task.ts
Labels: build

#4287 endregion snippet extraction does not require tag
  __tests__/unit/node/markdown/plugins/snippet.test.ts
  src/node/markdown/plugins/snippet.ts
Labels: cr-tracked
